### ISSUE TITLE
Main Page (Home Screen)

### ISSUE THREAD

**Issue by clift3** [team-mjw/TenDenMobileApp#1]
Main Page which includes the **Main Page** and **Devices Pop-up** sections of the 2nd report (except for the add device page).

List of features:

- Picture of light bulb that reflects the current state of the bulb.
- Toggle that turns it on or off.
- Dropdown list with device names
- Link to an Add Device page
- Side menu for the app settings. Currently this includes:
 -- Color Scheme 
 -- About

**Comment by jokabe** [comment]
Finished features:
1) Picture of light bulb that reflects the current state of the bulb
2) Toggle that turns it on or off
3) Side menu for the app settings

Need to work on:
1) Dropdown with device names
2) Link to "Add Device" page
3) Link to "Device Settings" page

**Comment by jokabe** [comment]
Finished Features:
- List of Devices Popup windows
- Button to the "Add a Device" Page
