### ISSUE TITLE
Alert Page

### ISSUE THREAD

**Issue by clift3** [team-mjw/TenDenMobileApp#5]
Page to enable/disable weather alerts.
Features:
- A toggle to enable/disable weather alerts.
- A description of the function
- A back button that leads to the device settings page.

**Comment by jokabe** [comment]
- Weather Alerts are now connected to the Data source
- Still, need to allow the user to set their preferred alert cycles

**Comment by jokabe** [comment]
- Weather Alerts are fetched every 30 minutes from the data source
- Alert-Page is completed with the needed functions
